Mehtap/terms(FE)
WomenPlusPlus/deploy-impact-23-shift-4 pull request #87
Opened 2023-10-14 20:22 UTC by mehtapy

2023-10-15 17:49 UTC, albarkauss commented
Looks good! 👍 
Do we need  the `regtest` ? or we can delete that?

2023-10-16 11:39 UTC, mehtapy commented
No sorry we dont need the regtest file it was only for testing

2023-10-16 13:50 UTC, gitadventurer241 requested changes

2023-10-16 13:50 UTC, gitadventurer241 commented on client/src/components/pages/register/regtest.jsx
> +export default Register;
Can you delete this file ?

2023-10-18 08:15 UTC, gitadventurer241 commented on client/src/components/pages/register/regtest.jsx
> +export default Register;
@mehtapy

2023-10-20 12:17 UTC, albarkauss approved these changes

2023-10-20 12:18 UTC, merged